### ISSUE TITLE
cannot compile with template-haskell-2.11

### ISSUE THREAD

**Issue by jwaldmann** [byorgey/haxr#14]
ghc-8 comes with template-haskell-2.11, and this gives
```
[6 of 8] Compiling Network.XmlRpc.THDeriveXmlRpcType ( Network/XmlRpc/THDeriveXmlRpcType.hs, dist/build/Network/XmlRpc/THDeriveXmlRpcType.o )

Network/XmlRpc/THDeriveXmlRpcType.hs:40:14: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _ n _ [RecC c fs] _
```
Cf. https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#template-haskell-2.11.0.0

**Comment by byorgey** [comment]
Thanks for the report!  Looks like this shouldn't be too hard to fix.  It also reminded me to update the `.travis.yml`.

**Comment by byorgey** [comment]
https://github.com/byorgey/haxr/commit/4c1395f07810a8f18eceb3f4e6525277fd80652c ought to do it, waiting for the Travis build to complete.

**Comment by byorgey** [comment]
Predictably, it took several more tries, but everything seems to be building cleanly now.  Released as `haxr-3000.11.1.4`.

**Comment by jwaldmann** [comment]
nice, thanks!
